"""add attendance indexes

Revision ID: ac6624e2e97d
Revises: db13cba79681
Create Date: 2026-09-18 17:23:14.521120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6624e2e97d'
down_revision: Union[str, Sequence[str], None] = 'db13cba79681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attendance_date', 'attendance', ['attendance_date'], unique=False)
    op.create_index('ix_attendance_employee_date', 'attendance', ['employee_id', 'attendance_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_employee_date', table_name='attendance')
    op.drop_index('ix_attendance_date', table_name='attendance')
    # ### end Alembic commands ###
