"""add working minutes to attendance

Revision ID: db13cba79681
Revises: 8c6cc91e998f
Create Date: 2026-09-17 10:17:58.902884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db13cba79681'
down_revision: Union[str, Sequence[str], None] = '8c6cc91e998f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('working_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'working_minutes')
    # ### end Alembic commands ###
